spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${PROFILES_DB_URL:jdbc:postgresql://postgres:5432/profiles_db}
    username: ${PROFILES_DB_USER:profiles_app}
    password: ${PROFILES_DB_PASSWORD:change_me_profiles_db_password}
  ssl:
    bundle:
      jks:
        grpc-server-tls:
          keystore:
            location: classpath:profiles-service.p12
            password: changeit
          truststore:
            location: classpath:truststore.jks
            password: changeit

internal:
  server:
    ssl:
      key-store: classpath:profiles-service.p12
      key-store-password: changeit
      trust-store: classpath:truststore.jks
      trust-store-password: changeit
