parent=keycloak
import=common/keycloak

styles=css/login.css
meta=viewport==width=device-width,initial-scale=1

kcFormClass=connect-form
kcFormGroupClass=form-group
kcLabelClass=connect-label
kcLabelWrapperClass=field-label
kcInputClass=connect-input
kcInputWrapperClass=field-control
kcInputGroup=connect-input-group
kcInputErrorMessageClass=field-error
kcFormOptionsClass=form-options
kcFormOptionsWrapperClass=form-options-inner
kcFormButtonsClass=form-buttons
kcFormButtonsWrapperClass=form-buttons-inner
kcFormSettingClass=form-settings
kcButtonClass=connect-button
kcButtonPrimaryClass=btn-primary
kcButtonDefaultClass=btn-secondary
kcButtonSecondaryClass=btn-secondary
kcButtonLargeClass=button-large
kcButtonBlockClass=button-block
kcMarginTopClass=flow-margin-top
kcFormPasswordVisibilityButtonClass=toggle-pw
kcSignUpClass=flow-info
kcInfoAreaWrapperClass=flow-info-inner
kcSelectAuthListClass=select-auth-list
kcSelectAuthListItemClass=select-auth-item
kcSelectAuthListItemIconClass=select-auth-icon
kcSelectAuthListItemBodyClass=select-auth-body
kcSelectAuthListItemHeadingClass=select-auth-title
kcSelectAuthListItemDescriptionClass=select-auth-description
kcSelectAuthListItemArrowClass=select-auth-arrow
kcLoginOTPListClass=otp-choice
kcLoginOTPListInputClass=otp-choice-input
kcLoginOTPListItemHeaderClass=otp-choice-header
kcLoginOTPListItemTitleClass=otp-choice-title
