spring:
  config:
    activate:
      on-profile: local
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  datasource:
    url: ${SWIPES_DB_URL:jdbc:postgresql://127.0.0.1:5435/swipes_db}
    username: ${SWIPES_DB_USER:swipes_app}
    password: ${SWIPES_DB_PASSWORD:change_me_swipes_db_password}
