spring:
  application:
    name: swipes-service
  config:
    import: "optional:file:services/swipes-demo/.env.properties"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${SWIPES_DB_URL:jdbc:postgresql://127.0.0.1:54335/swipes_db}
    username: ${SWIPES_DB_USER:swipes_app}
    password: ${SWIPES_DB_PASSWORD:change_me_swipes_db_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  codec:
    max-in-memory-size: 2MB

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2s

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9080/realms/spring/protocol/openid-connect/certs
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: 1
      batch-size: 131072        # 128kb
      linger-ms: 20

      buffer-memory: 67108864  # 64MB
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8040

services:
  profiles:
    base-url: http://localhost:8010/api/v1/profiles

kafka:
  topics:
    profile-created: profile.created
    profile-deleted: profile.deleted

