spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  datasource:
    url: ${MATCH_DB_URL}
    username: ${MATCH_DB_USER}
    password: ${MATCH_DB_PASSWORD}
