spring:
  config:
    activate:
      on-profile: local
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  datasource:
    url: ${CONSUMER_DB_URL:jdbc:postgresql://127.0.0.1:5435/consumer_db}
    username: ${CONSUMER_DB_USER:consumer_app}
    password: ${CONSUMER_DB_PASSWORD:change_me_consumer_db_password}
